apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-galera
  labels:
    app: mariadb-galera
spec:
  serviceName: galera-cluster
  podManagementPolicy: "OrderedReady"
  replicas: 3
  selector:
    matchLabels:
      app: mariadb-galera
  template:
    metadata:
      labels:
        app: mariadb-galera
    spec:
      securityContext:
        runAsUser: 27
        runAsGroup: 27
        fsGroup: 27
      serviceAccount: mariadb
      nodeSelector:
        node-role.kubernetes.io/compute: 'true'
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mariadb-galera
              topologyKey: kubernetes.io/hostname
      containers:
      - name: mariadb-galera
        image: YOUR_REGISTRY_URL/mariadb/mariadb-galera:10.4
        imagePullPolicy: IfNotPresent 
        env:
        - name: SERVICE_NAME
          value: galera-cluster
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 3306
          name: mariadb
          protocol: TCP
        - containerPort: 4567
          name: replication-tcp
          protocol: TCP
        - containerPort: 4567
          name: replication-udp
          protocol: UDP
        - containerPort: 4568
          name: galera-ist
          protocol: TCP
        - containerPort: 4444
          name: galera-sst
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - '-c'
              - /liveness-probe.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - '-c'
              - /readiness-probe.sh
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: 8Gi
            cpu:    2
          limits:
            memory: 12Gi
            cpu:    4
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: config-map
          mountPath: /tmp/mariadb-config
      volumes:
      - name: config-map
        configMap:
          name: galera-config-cm
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: mariadb-sc
        resources:
          requests:
            storage: 50Gi
        accessModes: [ "ReadWriteOnce" ]
        selector:
          matchLabels:
            app: mariadb-galera
  updateStrategy:
    type: OnDelete